#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

alias v='vim'
alias r='ranger'
alias z='zathura'

set -o vi

export LANG=en_US.UTF-8

export XDG_CONFIG_HOME="$HOME/.config"
